# Generated by Django 4.2 on 2023-04-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Welcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('details', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Welcome',
                'verbose_name_plural': 'Welcomes',
            },
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
    ]
